Update package.json
expo/sentry-expo pull request #153
Opened 2020-10-23 01:31 UTC by zibs

Currently getting a warning after `npx pod-install` with 
```
Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-updates
```
When using 
```
"sentry-expo": "^3.0.2",
"expo-updates": "^0.3.5",
```

2020-10-28 19:33 UTC, cruzach requested changes

2020-10-28 19:33 UTC, cruzach commented on package.json
> +    "expo-updates": "~0.3.0",
```suggestion
    "expo-updates": "~0.3.5",
```

this latest version will be installed anyways, so might as well be explicit 👍 

can you run `yarn` and commit the changes to `yarn.lock`?

2020-10-28 20:03 UTC, zibs commented
Thanks, done!

2020-10-28 20:15 UTC, cruzach approved these changes
aaaand thanks again **again** @zibs ! 🥇

2020-10-28 20:15 UTC, merged

2020-10-28 20:17 UTC, zibs commented
You're very welcome! Thanks for all your work too! Now to just get those OTA source-maps to work... 😆

2020-10-28 21:08 UTC, cruzach commented
yeah, sorry I'm not so much help there :/ it's too bad we aren't getting any user-facing error messages from Sentry

FYI sentry-expo@3.0.3 is released with your fixes 🚀

2020-10-29 15:41 UTC, gesposito commented
Just want to mention that this change seems to be incompatible with Expo <39

2020-10-29 15:52 UTC, cruzach commented
yeah we could've made this `>=0.2.4` instead, but there have been quite a few bug fixes to `expo-updates` so it's good to recommend upgrading wherever we can I think. If you want to use the latest version of `sentry-expo` on earlier SDKs @gesposito you could always use `patch-package`